name: "Run E2E Tests"
description: "Runs VS Code End-to-End Tests for the Colab extension"

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"
    - run: npm ci
      shell: bash
    - name: Download generated config
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: generated-config
        path: src
    # Tp run e2e test with real secrets
    - name: Generate config with real secrets
      run: npm run generate:config
      shell: bash
    - name: npm run test:e2e:headless (Linux)
      if: runner.os == 'Linux'
      run: npm run test:e2e:headless
      shell: bash
      env:
        SCREENSHOTS_DIR: /tmp/test-resources/screenshots/
    - name: npm run test:e2e
      if: runner.os != 'Linux'
      run: npm run test:e2e
      shell: bash
      env:
        SCREENSHOTS_DIR: /tmp/test-resources/screenshots/
    - name: upload screenshots
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: screenshots
        path: /tmp/test-resources/screenshots/
    - name: upload exthost.log
      if: failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: exthost log
        path: /tmp/test-resources/settings/logs/*/window1/exthost/exthost.log
